### ISSUE TITLE
create field notes tree structure

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/fieldnotes-restructuring#1]
For the "course archives" links found here: http://fieldnotes.makingandknowing.org/mainSpace/space.menu.html, map out the link tree.
Collapsing the semester+year and then "field notes," organize by each student's name

**Comment by njr2128** [comment]
Update: all missing items have been identified and we are ready to reorganize based on the new mapping

**Comment by gschare** [comment]
Update to the update: actually we forgot about Fall 2017, the most recent semester.

**Comment by njr2128** [comment]
Fall 2017 done, so all tasks here have been completed
