### ISSUE TITLE
Use generated mapping to arrange files into a hierarchical directory structure

### ISSUE THREAD

**Issue by gschare** [cu-mkp/fieldnotes-restructuring#12]
Now that we have generated a mostly-complete `mapping.csv` and found corrected most of the broken links in `missing.csv`, we are ready to use the mapping to quite simply iterate over each of the rows in the spreadsheet, locate the file named in the first column and rename it (creating intermediate folders along the way) to the second column.
This can be done just using bash scripting, and although the Python script should prevent this, we should throw errors in case we try to rename a file to something that already exists.

**Comment by gschare** [comment]
[restructure.py](https://github.com/cu-mkp/fieldnotes-reindex/blob/main/restructure.py) is in-progress on this

**Comment by njr2128** [comment]
this has been completed
