### ISSUE TITLE
assess loose html files in content/ in S3

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/fieldnotes-restructuring#17]
These are any files that were not outright linked to from the intermediate index pages, and so they have not been reorganized/restructured into the new system.

Go through these to determine what they are and whether they have content that should be preserved and where they belong. (easiest way to do this now is to use https://fieldnotes.makingandknowing.org/content/index.html)
--> @njr2128 

After this, if the files SHOULD be preserved, determine method to add them to their proper location and index
--> @gschare (at a later point and probably in a new issue)

**Comment by njr2128** [comment]
Work from the most recent listing of the restructured S3 bucket

**Comment by njr2128** [comment]
I have gone through the entire list and put my results in the attached spreadsheet (also in the GD with the same name)
[2021-07-14_S3-content_index.xlsx](https://github.com/cu-mkp/fieldnotes-restructuring/files/6843303/2021-07-14_S3-content_index.xlsx)


There are 3 columns:
1. File name and link
2. Notes - identification (if possible), description of contents
3. Action - with one of three values
     a.  Remove - don't need this page/file
     b. Add to [Semester+year] -it has been identified and should be added to the listings in that semester and year
     c. [blank] - need to determine what to do with this

The majority of the [blank] action items are either student/staff profiles or teaching resources:
- The teaching resources should probably be separated from the `content/` directory as they are not fieldnotes proper, though they should be preserved (and reviewed separately by NJR and PHS)
- The profiles: either need to be added to their semesters or removed. The staff profiles don't have a related semester, so they perhaps need to be put together or just removed

**Comment by njr2128** [comment]
Next steps:

- "Add to" items in the "Action" column are handled by #19 
- "Remove" items should likely be put into one directory together (issue to be created)
- [blank] - need review (issue to be created)

**Comment by gschare** [comment]
"Add to" items have been completed.

**Comment by njr2128** [comment]
outstanding tasks moved to #21
