### ISSUE TITLE
identify error in URL of GNS field notes

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/fieldnotes-restructuring#18]
As part of my work on #17, I came across the following field notes by GNS (Njeri Ndungu, SP16) but am experierincing an error with the non-S3 URL.

![image](https://user-images.githubusercontent.com/14779727/126204296-7110f067-b835-44f8-8cfd-ee9f407f423e.png)

The S3 Object URL takes me to the content (as it should): https://s3.amazonaws.com/fieldnotes.makingandknowing.org/content/GNS+-+Field+Notes+SP16+-+Mayerne+'or+coleur'++recipe+with+varnish.html

However, the equivalent one using the M&K domain returns an XML error.  I copy and paste this into my browser directly from S3 URI: `fieldnotes.makingandknowing.org/content/GNS - Field Notes SP16 - Mayerne 'or coleur' recipe with varnish.html` which converts into `https://fieldnotes.makingandknowing.org/content/GNS%20-%20Field%20Notes%20SP16%20-%20Mayerne%20'or%20coleur'%20recipe%20with%20varnish.html`

Could this have something to do with the single quote/tick characters? @gschare, any insights?

**Comment by gschare** [comment]
You're just missing a space:
https://fieldnotes.makingandknowing.org/content/GNS%20-%20Field%20Notes%20SP16%20-%20Mayerne%20'or%20coleur'%20%20recipe%20with%20varnish.html

```coleur'%20%20recipe``` as opposed to ```coleur'%20recipe```

**Comment by njr2128** [comment]
OMG thank you! I was staring at these URLs for waaay too long.
